name: test_login
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  pinput: ^5.0.1
  flutter_spinkit: ^5.2.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  video_player: ^2.9.5
  shimmer: ^3.0.0
  intl: ^0.20.2
  mockito: ^5.4.5
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets setup for images and icons
  assets:
    - assets/images/
    - assets/images/restaurant.jpg
    - assets/icons/
    - assets/video/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
